### ISSUE TITLE
Delete parts or update existing parts

### ISSUE THREAD

**Issue by aelray** [qmuntal/opc#18]
Hi,

I'm trying to update a file in a package. I naively tried to simply re-add it after modification but this returns the following:

```
a package shall not contain equivalent part names
```

Is it possible to delete a part in the package or even just update it with a modified version?

**Comment by qmuntal** [comment]
One a Part name has been used you cannot add more parts with the same name, even if it is the same part with some modifications. The zip spec does allow to have duplicated file names, but you would end up storing the same file twice as due to the sequential nature of a zip package it is very difficult to modify or delete a random file without having to rewrite the whole zip package. To avoid shooting yourself in the foot OPC forbids parts with duplicated names, 

If you have an `opc.Reader` and need to rewrite some of its parts then `NewWriterFromReader` does not work for you, as it will copy all the parts from the `opc.Reader` to the `opc.Writer`. What you can do is, having that function as reference ,implement your own function that just copies the parts that won't be modified and add them the other parts in a later step.

**Comment by aelray** [comment]
So you propose to filter out the file in this loop:

https://github.com/qmuntal/opc/blob/5df7fe405ba9aaa3b9998bc33c6fb577cc7faeec/writer.go#L58-L72

?

**Comment by qmuntal** [comment]
Yep.

**Comment by aelray** [comment]
Works fine thank you for the hint.
